config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :posts do
    resources :likes, only:   [:create, :destroy]
    resources :comments, only:   [:new,:create, :destroy]
  end
  resources :stories, except:   [:edit, :update]
  get '/search', to: 'users#search'

  resources :users do
    member do
      post :follow
      delete :unfollow
      post :accept_request
      delete :reject_request
      delete :remove_follow_request

    end
    collection do
      get :friend_requests
    end
  end 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts
         has_many :comments, dependent: :destroy
         has_many :likes, dependent: :destroy
         has_one_attached :image
  has_many :stories, dependent: :destroy

  validate :correct_image_type
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :send_requests, foreign_key: :send_user_id, class_name: 'friendrequest', dependent: :destroy
  has_many :receive_users, through: :send_requests

  has_many :receive_requests, foreign_key: :receive_user_id, class_name: 'friendrequest', dependent: :destroy
  has_many :sending_users, through: :receiving_requests

  has_many :following_follows, foreign_key: :following_user_id, class_name: 'Follower', dependent: :destroy                                                                                                                                                                            
  has_many :followed_users, through: :following_follows, dependent: :destroy
                                                                                                                                                                                                                                                                                                                                                                                                                                                              
  has_many :followed_follows, foreign_key: :followed_user_id, class_name: 'Follower', dependent: :destroy
  has_many :followed_users, through: :followed_follows, dependent: :destroy


  validates :username, presence: true, length: {minimum:5 , maximum: 20}
  validates :username, presence: true, length: {minimum:5 , maximum: 20}
  validates :username, presence: true, length: {minimum:5 , maximum: 20}

  def correct_image_type
    if image.attached? && !image.content_type.in?(%w[image/jpeg image/png])
      errors.add(:image, ' must be jpeg and png')
    elsif image.attached? == false
      errors.add(:image, 'must have an image attached')
    end
  end


  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show follow unfollow accept_request reject_request remove_follow_request]
  def index
    @users = User.page(params[:page])
  end

  def show
    @stories = @user.stories
    @posts = @user.posts
  end

  def follow
    if @user.public_account?
      @user.follower_users << current_user
      flash[:alert] = 'Followed'
    else
      @user.sending_users << current_user
      flash[:alert] = 'Requested'
    end
    redirect_to users_path
  end

  def unfollow
    if @user.follower_users.delete(current_user)
      flash[:alert] = 'unfollowed'
      redirect_to users_path
    end
  end

  def accept_request
    current_user.follower_users << @user
    authorize @user
    if Request.delete_request(@user.id, current_user.id)
      flash[:notice] = 'request accepted'
      redirect_to users_path
    end
  end

  def reject_request
    authorize @user
    if Request.delete_request(@user.id, current_user.id)
      flash[:notice] = 'request rejected'
      redirect_to users_path
    end
  end

  def remove_follow_request
    authorize @user
    if Request.delete_request(current_user.id, @user.id)
      flash[:notice] = 'request removed'
      redirect_to users_path
    end
  end

  def search
    @parameter = params[:search].downcase
    @results = User.all.where('username LIKE :search', search: "%#{@parameter}%")
    end

  private

  def set_user
    @user = User.find(params[:id])
  end
  end
  

app/views/users/friend_request.html.erb
<div class= "jumbotron shadow">
Hey <%= current_user.username %>!!
<br>
<h1>Friend Requests</h1>
<% current_user.sending_users.each do |user|%>
  <%= user.username %>
  <%= link_to 'accept',accept_request_user_path(user),method: :post,class:"btn-info btn-sm shadow"%>
  <%= link_to 'reject',reject_request_user_path(user),method: :delete,class:"btn-warning btn-sm shadow"%>
<%end%>
<br>
<div>
<br />
<%= link_to 'Back',root_path,class:"btn btn-primary shadow"%>

app/views/users/index.html.erb
<%@users.each do |user|%>
    <h3><%= user.username %></h3>
 <% if current_user!=user%>
    <% if current_user.following_users.include?(user)%>
      <%= link_to 'unfollow',unfollow_user_path(user),method: :delete,class:"btn btn-warning btn-sm shadow"%>
    <br>
    <% elsif current_user.receiving_users.include? (user)%>
      <%= link_to 'remove request',remove_follow_request_user_path(user), method: :delete,class:"btn btn-danger btn-sm shadow"%>
    <%else%>
      <%= link_to 'follow',follow_user_path(user),method: :post,class:"btn btn-info btn-sm shadow"%>
    <%end%>
  <%end%>
    <br>
<%end%>
<br />
<div align="center" class="m-5">
<%= paginate @users %>
</div>
<br>
<%= link_to 'Back',root_path,class:"btn btn-primary shadow"%>

app/views/users/search.html.erb
<div class="jumbotron">
<% if @results.present?%>
<h1>Search Results</h1>
<% @results.each do |result|%>
<%= result.username%> <%= link_to 'show',user_path(result.id),class:" btn btn-info"%> <br/>
<b>Name:</b><%= result.firstname%>
<b>Email:</b><%= result.email%>
<%end%>
</div>
<br>
<%else%>
No user found
<%end%>
<%= link_to 'Back',root_path,class:"btn btn-primary"%>

app/views/users/show.html.erb
<div class="row justify-content-md-center profile-wrapper">
<div class="col-md-4 text-center">
<%= image_tag("user.jpeg", :width => "152", :height => "152", class: "round-img") %>
</div>
<div class="col-md-8">
<div class="row">
<p class= "username"><%= @user.username %></p>
<% if @user == current_user %>

<%= link_to "Edit profile", edit_user_registration_path, class:"btn btn-outline-dark btn-sm" %>

<% end %>

</div>

<div class="row">
<p class= "email"><%= @user.email %></p>
</div>

</div>
</div>


<%if @user.public_account?%>
<div class="conatiner mt-5">
<div class="shadow p-4 max-auto"style="max-width:400px">
 <h2>Stories</h2>
<% @stories.each do |story| %>
  <div class="position-relative me-2">
    <%= image_tag(story.image,style:'width:20%;border-radius:30px;')%>
    <br/>
    <%=story.user.username%>
  </div>
<%end%>
</div>
</div>
<br/>
<%=@post%>
<div style="width:400px;height:auto">
<%= image_tag(current_user.image,style:'width:20%;border-radius:30px;')%>
<br />
<h3><%= current_user.firstname%></h3>
</div>
<div>
Stories:
<%= render 'stories/index'%>
</div>
<br />
<div class="card mb-3 shadow" style="max-width: 540px;">
<div class="contaier  m-3">
<h1> Posts</h1>
<% @posts.each do |post| %>
    <br>
    <b> Title:</b> <%= post.title %>
     <br>
     <b>Description:</b> <%= post.description %>
  <%(post.images).each do |image|%>
    <div style="width:50px;height:auto;">
      <%= image_tag(image,class:"contaier text-center")%>
    </div>
  <%end%>
    <br><%= (post.likes.count) == 1 ? 'Like' : 'Likes'%><%=post.likes.count%>
    <%= like_check(post)%>
  <%= form_with(model: [post, post.comments.build ], remote: true) do |form| %>
    <%= form.label :Comment_here %>
    <br>
    <%= form.text_field :body, required: true %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <br>
    <%= form.submit class:"btn btn-success" %>
  <%end%>
       <%= render partial: 'comments/comment', collection: post.comments ,as: :comment%>
<%end%>
<br>
</div>
</div>
  <%else%>
  Account is private
<%end%>
<%= link_to 'Back',root_path,class:"btn btn-primary"%>