config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :posts do
    resources :likes, only:   [:create, :destroy]
    resources :comments, only:   [:new,:create, :destroy]
  end
  resources :stories, except:   [:edit, :update]
  get '/search', to: 'users#search'

  resources :users do
    member do
      post :follow
      delete :unfollow
      post :accept_request
      delete :reject_request
      delete :remove_follow_request

    end
    collection do
      get :friend_requests
    end
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
      def index
        user = current_user.followed_users.ids
        @posts = Post.where(user_id: user)
        @stories = Story.where(user_id: user)
      end
    end
  end
  

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Instagram</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path ,class:"btn btn-outline-dark btn-sm"%>
        </li>
        </li>
        <% if current_user %>
        <li class="nav-item">
        <%= link_to 'All Posts', posts_path ,class:"btn btn-outline-dark btn-sm" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Add Posts', new_post_path ,class:"btn btn-outline-dark btn-sm"%>
      </li>
       

        <li class="nav-item">
        <%= link_to 'Add story',new_story_path,class:"btn btn-outline-dark btn-sm" %>
        </li>

        <li class="nav-item">
        <%= link_to 'Stories',stories_path,class:"btn btn-outline-dark btn-sm" %>
        </li>
        <li class="nav-item">
        <%= link_to "Profile", user_path(current_user),class:"btn btn-outline-dark btn-sm"%>
        </li>
        <li class="nav-item">
            <%= link_to 'Sign Out',destroy_user_session_path,method: :delete,class:"btn btn-outline-dark btn-sm" %>
        </li>
    
        <%= form_tag(search_path, :method => "get")  do%>
            <div class="input-group d-flex">
                <%= search_field_tag :search, params[:search], placeholder: "Type ", class: "form-control me-2",required: true, style: "margin-left: 150px" %>
                <div class="input-group-btn">
                    <%= button_tag "Search for Users", :class => 'btn btn-info glyphicon glyphicon-search', :name => nil%>
                </div>
            </div>
          <%end%>
        

        <%else%>

      <li class="nav-item">
       <%= link_to 'Log In',new_user_session_path,class:"nav-link text-dark" %>
        </li>
      <li class="nav-item">
        <%= link_to 'Sign up', new_user_registration_path ,class:"nav-link text-dark" %>
        </li>


    <%end%>



    </div>
  </div>
</nav>

app/views/home/_sidebar.html.erb
More
<div class=" flex-column flex-shrink-0 p-3 text-bg-light shadow" style="width: 200px;float:right;">
    <a href="/" class="d-flex align-items-center  text-dark text-decoration-none  side">
    <aside> Followers:<%= current_user.follower_users.count%>
     <% for user in current_user.follower_users %>
       <%= user.username %>
    <% end %>
    </aside>
<br>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <%= link_to 'All users',users_path,class:"btn btn-outline-dark btn-sm"%>
      </li>
      <br>
      <li>
          <%= link_to 'Add story',new_story_path,class:"btn btn-outline-dark btn-sm" %>
      </li>
      <br>
      <li>
          <%= link_to 'Requests',friend_requests_users_path,class:"btn btn-outline-dark btn-sm"%>
      </li>
      <br>
    </ul>
    <hr>

  </div>

app/views/home/index.html.erb
<h1 style="margin-left: 250px; margin-top: 100px;">Welcome to Instagram Clone</h1>