config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :posts do
    resources :likes, only:   [:create, :destroy]
    resources :comments, only:   [:new,:create, :destroy]
  end
  resources :stories, except:   [:edit, :update]
  get '/search', to: 'users#search'

  resources :users do
    member do
      post :follow
      delete :unfollow
      post :accept_request
      delete :reject_request
      delete :remove_follow_request

    end
    collection do
      get :friend_requests
    end
  end 
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validate :correct_image_type
  after_create :expire_job

  def expire_job
    StoriesExpireJob.set(wait: 24.hours).perform_later(id, user.id)
  end
 

  def correct_image_type
    if image.attached? && !image.content_type.in?(%w[image/jpeg image/png])
      errors.add(:image, 'must be jpeg and png')
    elsif image.attached? == false
      errors.add(:image, 'must have an image attached')
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
    def index
      @stories = Story.all
    end
  
    def new
    
      @story = Story.new
    end
  
    def create
     
      if @story = current_user.stories.create(story_params)
        flash[:notice] = 'Story Created'
        redirect_to stories_path
      else
        flash[:notice] = 'Story Creation failed'
      end
    end
  
    def destroy
      @story = Story.find(params[:id])
      if @story.destroy
        flash[:notice] = 'Story deleted'
        redirect_to root_path
      else
        flash[:notice] = 'Story deletion failed'
      end
    end
  
    private
  
    def story_params
      params.require(:story).permit(:image)
    end
  end
  

app/views/stories/_index.html.erb
<% current_user.stories.each do |story| %>
    <div style="width:20px;height:auto;">
      <%= image_tag(story.image,style:'width:200%;border-radius:300px;')%>
    </div><br/>
    <%= link_to 'Delete Story',story_path(story), method: :delete ,class:" btn-danger btn-sm"%>
  
  <%end%>
  

app/views/stories/index.html.erb
<%= render 'index'%>
<%=link_to 'Back',root_path%>

app/views/stories/new.html.erb
<%= form_with scope: :story, url: stories_path, local: true do |f| %>
    <h1>Create Stories</h1>
    <div class="field">
        <%= f.label :Add_image %><br />
        <%= f.file_field :image ,required: true,accept: "image/png,image/jpg,image/jpeg"%>
      </div>
      <br>
    <p>
        <%= f.submit  class: "btn btn-warning" %>
      </p>
    
    <% end %>
    <%= link_to 'Back',root_path,class:"btn btn-primary"%>
    